JBB-Web/config/routes.rb
Rails.application.routes.draw do

  #mailer
  get '/user_mailers/welcome'
  post '/user_mailers/welcome'

  resources :users


  scope "(:locale)", locale: /en|pt/ do

    #root
    # get '/:locale' => 'welcome#index', :as => 'home'
    # get '/:locale' => 'welcome#index', :as => 'root'
    root 'welcome#index', :as => 'home'
    root 'welcome#index', :as => 'root'

    get '/education_choice' => 'welcome#education_choice'


    #users
    get '/users/new' => 'users#new'
    post '/users/new' => 'users#create', :as => 'create_user'
    get '/users/:id' => 'users#show', :as => 'user_show'
    get '/users/edit/:id' => 'users#edit', :as => 'user_edit'
    get '/users/my_requests/:id' => 'users#my_requests', :as =>'user_my_requests'

    patch '/users/update/', controller: 'users', action: 'update', :as => 'update_user'
    patch '/users/update/:id', controller: 'users', action: 'update_password', :as => 'update_user_password'
    patch '/users/destroy/', controller: 'users', action: 'destroy', :as => 'destroy_user'

    #sessions_login
    get    '/sign_in'   => 'sessions#new'
    post   '/sign_in'   => 'sessions#create', :as => 'sign_in_path'
    get '/sign_out' => 'sessions#destroy'

    #root
    get 'sessions/new'
    get 'trails/new'

    #Visitations
    resources :visitations, :except => [:show, :update, :destroy]

    get 'visitations/home', as: 'home_visitation'
      get 'visitations/show_employee', as: 'show_visitation_employee'
    get 'visitations/show_user', as: 'show_visitation_user'
    get 'visitations/index_employee', as: 'index_visitation_employee'
    get 'visitations/index_user', as: 'index_visitation_user'
    get 'visitations/user_information', as: 'visitations_user_information'

    #Visitation Employee
    get 'visitations/accept_visitation_employee', as: 'get_accept_visitation_employee'
    post 'visitations/accept_visitation_employee', as: 'post_accept_visitation_employee'

    get 'visitations/refuse_visitation_employee', as: 'get_refuse_visitation_employee'
    post 'visitations/refuse_visitation_employee', as: 'post_refuse_visitation_employee'

    get 'visitations/cancel_visitation_employee', as: 'get_cancel_visitation_employee'
    post 'visitations/cancel_visitation_employee', as: 'post_cancel_visitation_employee'

    get 'visitations/delete_visitation_employee', as: 'get_delete_visitation_employee'
    post 'visitations/delete_visitation_employee', as: 'post_delete_visitation_employee'

    #Visitation User
    get 'visitations/advices', as: 'get_visitation_advices'
    get 'visitations/cancel_visitation_user', as: 'get_cancel_visitation_user'
    post 'visitations/cancel_visitation_user', as: 'post_cancel_visitation_user'

    #sessions_login
    get 'visitations/delete_visitation_user', as: 'get_delete_visitation_user'
    post 'visitations/delete_visitation_user', as: 'post_delete_visitation_user'

    get    'sign_in'   => 'sessions#new'
    post   'sign_in'   => 'sessions#create'
    delete '/sign_out' => 'sessions#destroy'
    delete 'sign_out'  => 'sessions#destroy'


    #root 'sessions#new'

    get 'events/new' => 'events#new', as: 'events'
    post 'events/new' => 'events#create', as: 'events_save'
    get 'events/show' => 'events#show', as: 'show_event'
    get 'events/show_user', as: 'show_event_user'
    get 'events/show_employee', as: 'show_event_employee'
    get 'events/index_user'
    get 'events/user_information', as: 'events_user_information'
    get 'events/index_employee', as: 'index_event_employee'
    post 'events/index_employee', as: 'index_event_employee_save'

    #Event Employee
    get 'events/accept_event_employee', as: 'get_accept_event_employee'
    post 'events/accept_event_employee', as: 'post_accept_event_employee'

    get 'events/refuse_event_employee', as: 'get_refuse_event_employee'
    post 'events/refuse_event_employee', as: 'post_refuse_event_employee'

    get 'events/cancel_event_employee', as: 'get_cancel_event_employee'
    post 'events/cancel_event_employee', as: 'post_cancel_event_employee'

    get 'events/delete_event_employee', as: 'get_delete_event_employee'
    post 'events/delete_event_employee', as: 'post_delete_event_employee'

    #event User
    get 'events/cancel_event_user' => 'events#cancel_event_user'
    post 'events/cancel_event_user' => 'events#cancel_event_user'

    #Map
    get 'maps/jbb_map', as: 'get_jbb_map'
    post 'maps/jbb_map', as: 'post_jbb_map'

    # schedule route
    get 'events/index_calendar_month' => 'events#index_calendar_month', as: 'show_event_calendar'
    get 'visitations/index_calendar_month' => 'visitations#index_calendar_month', as: 'show_visitation_calendar'

    get 'events/index_calendar_week' => 'events#index_calendar_week', as: 'show_event_calendar_week'
    get 'visitations/index_calendar_week' => 'visitations#index_calendar_week', as: 'show_visitation_calendar_week'

  end

end

JBB-Web/app/models/visitation.rb
class Visitation < ApplicationRecord
  belongs_to :user

  def start_time
    self.date
  end

  # validation of period
	validates :period, presence: true

	# validation of date
	validates :date, presence: true

  validate :not_mondays

  def not_mondays
    if (self.date.wday == 1)
      errors.add(:date, I18n.t(:not_mondays))
    end
  end

  #validation of visitants_paying
  validates :visitants_paying, presence: true
  # validation of description
  validates :description, presence: true, length: { minimum: 5, maximum: 300 }
  #validation of visitants_amount
  validates :visitants_amount, presence: true
  validate :validate_visitants_amount


  #status
  def set_status_default
    self.status = "Aguardando confirmacao"
  end

  def self.initial_cost
    return 0
  end

  def amount_payed
    if (self.status <=> "Agendado") == 0
      return self.visitation_cost
    else
      return 0
    end
  end

  # validate the amount of visitors informed by the user
  def validate_visitants_amount
    if (self.visitants_amount > 45)
      errors.add(:visitants_amount, I18n.t(:too_much_visitors))
    elsif (self.visitants_amount < 1)
      errors.add(:visitants_amount, I18n.t(:zero_visitors))
    elsif (self.visitants_amount < self.visitants_paying)
      errors.add(:visitants_amount, I18n.t(:more_paying_than_visitors))
    end
  end


  # calculate the visitation cost
  def set_visitation_cost
    if (self.visitation_type <=> "Escola publica") == 0
      self.visitation_cost = 0
    else
      self.visitation_cost = (self.visitants_paying * 5)
    end
  end

  #status
  def set_status_default
    self.status = "Aguardando confirmacao"
  end


  #status
  def set_status_default
    self.status = "Aguardando confirmacao"
  end


  def canceled_by_employee
    self.status = "Cancelado por funcionario"
  end


  def canceled_by_user
    self.status = "Cancelado pelo usuario"
  end


  def refused_by_employee
    self.status = "Recusado por funcionario"
  end


  def accepted_by_employee
    self.status = "Agendado"
  end
end

JBB-Web/app/controllers/visitations_controller.rb
class VisitationsController < ApplicationController
  before_action except: [:home, :new, :create, :show_user, :show_employee, :index_calendar_month, :advices, :index_calendar_week] do
    @visitation = Visitation.find(params[:id])
  end

  #home
  def home
  end

  #new
  def new
    @visitation = Visitation.new
  end

  #Create a visit
  def create
    @visitation = Visitation.new(visitation_params)
    @visitation.user_id = current_user.id
    @visitation.set_status_default
    @visitation.set_visitation_cost
    if @visitation.save
      UserMailer.change_status_visitation(@visitation).deliver_now
      flash[:success] = t(:successful_visit_request)
      redirect_to "/#{I18n.locale}/visitations/advices"
    else
      flash[:warning] = t(:request_not_made)
      render 'new'
    end
  end

  #cancel visitation
  def cancel_visitation_user
    @visitation.canceled_by_user
    if @visitation.save
      UserMailer.change_status_visitation(@visitation).deliver_now
      flash[:warning] = t(:visitation_canceled_user)
      redirect_to "/#{I18n.locale}"+show_visitation_user_path
    end
  end


  #show
  def show_user
    @visitation = Visitation.where(user_id: current_user.id)
  end

  def show_employee
    @visitations = Visitation.all
    @visitations_sorted = @visitations.sort_by {|visitation| visitation.status}
    @visitation_types = Visitation.all.select(:id, :visitation_type)
    @sum_of_payments = Visitation.initial_cost
    @visitations.each do |visit|
      @sum_of_payments += visit.amount_payed
    end
    period = params[:period]
    select_pdf(VisitationsPdf.new(period))
  end


  #index
  def index_user
  end

  def index_employee
  end

  #refuse_confirmation
  def refuse_visitation_employee
    @visitation.refused_by_employee
    if @visitation.save
      UserMailer.change_status_visitation(@visitation).deliver_now
      flash[:success] = t(:visitation_refused)
      redirect_to "/#{I18n.locale}"+show_visitation_employee_path
    else
      flash[:warning] = t(:not_objectionable_visitation)
      redirect_to "/#{I18n.locale}"+show_visitation_employee_path
    end
  end

  #cancel_confirmation
  def cancel_visitation_employee
    @visitation.canceled_by_employee
    if @visitation.save
      UserMailer.change_status_visitation(@visitation).deliver_now
      flash[:success] = t(:visitation_canceled)
      redirect_to "/#{I18n.locale}"+show_visitation_employee_path
    else
      flash[:warning] = t(:not_cancellable_visitation)
      redirect_to "/#{I18n.locale}"+show_visitation_employee_path
    end
  end

  #delete_visitation
  def delete_visitation_employee
    if @visitation.destroy
      flash[:success] = t(:visitation_removed)
      redirect_to "/#{I18n.locale}"+show_visitation_employee_path
    else
      flash[:warning] = t(:not_removable_visitation)
      redirect_to "/#{I18n.locale}"+show_visitation_employee_path
    end
  end

  #accept_visitation
  def accept_visitation_employee
    @visitation.accepted_by_employee
    if @visitation.save
      UserMailer.change_status_visitation(@visitation).deliver_now
      flash[:success] = t(:visitation_confirmed)
      redirect_to "/#{I18n.locale}"+show_visitation_employee_path
    else
      flash[:warning] = t(:not_confirmable_visitation)
      redirect_to "/#{I18n.locale}"+show_visitation_employee_path
    end
  end

  # schedule filter
  def index_calendar_month
    @visitations = Visitation.where("status = ? AND has_guide = ?", "Agendado", true)
  end

  #parameters
  private
  def visitation_params
    params.require(:visitation).permit(:date, :period, :status, :visitants_amount,
                                       :visitation_type, :groups_age, :objective,
                                       :spaces, :has_guide, :description,
                                       :visitants_paying, :visitation_cost)
  end
end

JBB-Web/app/views/visitations/accept_visitation_employee.html.erb
<p id="notice"><%= notice %></p>

<%= controller.redirect_to "/#{I18n.locale}"+show_visitation_path %>

JBB-Web/app/views/visitations/cancel_visitation_employee.html.erb
<p id="notice"><%= notice %></p>

<%= controller.redirect_to "/#{I18n.locale}"+show_visitation_path %>

JBB-Web/app/views/visitations/cancel_visitation_user.html.erb
<p id="notice"><%= notice %></p>

<%= controller.redirect_to "/#{I18n.locale}"+show_visitation_path %>

JBB-Web/app/views/visitations/delete_visitation_employee.html.erb
<p id="notice"><%= notice %></p>

<%= controller.redirect_to "/#{I18n.locale}"+show_visitation_path %>

JBB-Web/app/views/visitations/index_calendar_month.html.erb
<body id="page-top">
  <head>
    <link href="/vendor/bootstrap/css/bootstrap.css" rel="stylesheet">
    <link href="css/creative.css" rel="stylesheet">
  </head>
  <body id="aplication-body">
    <section id="services">
      <div class="container">
        <div class="row">
          <div class="col-lg-12 text-center">
            <h2 class="section-heading"><%= t(:visit_calendar) %></h2>
            <hr class="primary">
          </div>
        </div>
      </div>
    <div class="col-md-6 col-md-offset-3">
    <div class="actions">
      <%= link_to t(:search_by_week), "/#{I18n.locale}"+show_visitation_calendar_week_path, class: "btn btn-primary"%>
    </div>
    <br>
      <%= month_calendar events: @visitations do |date, visitations| %>
      <b><%= date.strftime("%d") %></b>
      <% visitations.each do |visitation| %>
      <div>
          <%= visitation.description %>
      </div>
      <% end %>
      <% end %>
   <div class= "actions" >
     <%if current_user%>
      <%= link_to t(:create_visit), "/#{I18n.locale}"+new_visitation_path, class: "btn btn-primary"%>
      <%end%>
    <a id="calendar" >
      <%= link_to t(:back), "/#{I18n.locale}", class: "btn btn-primary"%>
    </div>
    <br>
  </body>
</body>

JBB-Web/app/views/visitations/index_calendar_week.html.erb
<body id="page-top">
    <head>
      <link href="/vendor/bootstrap/css/bootstrap.css" rel="stylesheet">
      <link href="css/creative.css" rel="stylesheet">
    </head>
    <body id="aplication-body">
      <section id="services">
        <div class="container">
          <div class="row">
            <div class="col-lg-12 text-center">
                <h2 class="section-heading"><%= t(:visit_calendar) %></h2>
                <hr class="primary">
            </div>
          </div>
        </div>
  <div class="col-md-6 col-md-offset-3">
  <div class="actions">
    <%= link_to t(:search_by_month), "/#{I18n.locale}"+show_visitation_calendar_path, class: "btn btn-primary"%>
  </div>
  <br>
    <%= week_calendar number_of_weeks: 1 do |date, visitations| %>
    <b> <%= date.strftime("%d")  %> </b>
    <% visitations.each do |visitations| %>
    <div>
     <%= visitations.description %>
   </div>
   <% end %>
   <% end %>
   <div class= "actions" >
     <%if current_user%>
    <%= link_to t(:create_visit), "/#{I18n.locale}"+new_visitation_path, class: "btn btn-primary"%>
    <%end%>
    <a id="calendar" >
    <%= link_to t(:back), "/#{I18n.locale}", class: "btn btn-primary"%>
    </div>
  </div>
</body>

JBB-Web/app/views/visitations/index_employee.html.erb
<body>
    <head>
        <link href="/vendor/bootstrap/css/bootstrap.css" rel="stylesheet">
        <link href="css/creative.css" rel="stylesheet">
    </head>
    <body id="aplication-body">
        <section id="services">
            <div class="container">
                <div class="row">
                    <div class="col-lg-12 text-center">
                        <h2 class="section-heading"><%= t(:information_visit) %></h2>
                        <hr class="primary">
                    </div>
                </div>
            </div>
            <div class="col-md-6 col-md-offset-3">
            </div>
            <div class="container">
                <div class="row">
                    <div class="col-md-6 col-md-offset-3">
                        <div class = "actions">
                          <b><%= t(:user_info) %></b>
                          <td><%= link_to @visitation.user.name, "/#{I18n.locale}/visitations/user_information?id=#{@visitation.id}" %></td>
                        </div>
                        <br>
                        <div class = "actions" >
                            <b><%= t(:date_schedule) %></b>
                            <%= l(@visitation.date, format: :long) %>
                        </div>
                        <br>
                        <div class = "actions" >
                            <b><%= t(:scheduled_period) %></b>
                            <%= @visitation.period %>
                        </div>
                        <br>
                        <div class = "actions" >
                            <b><%= t(:social_reason) %></b>
                            <%= @visitation.visitation_type %>
                        </div>
                        <br>
                        <div class = "actions" >
                            <b><%= t(:status) %></b>
                            <%= @visitation.status %>
                        </div>
                        <br>
                        <div class = "actions" >
                            <b><%= t(:number_visitors) %></b>
                            <%= @visitation.visitants_amount %>
                        </div>
                        <br>
                        <div class = "actions" >
                            <b><%= t(:number_paying_visitors) %></b>
                            <%= @visitation.visitants_paying %>
                        </div>
                        <br>
                        <div class = "actions" >
                            <b><%= t(:visit_price) %></b>
                            <%= @visitation.visitation_cost %>
                        </div>
                        <br>
                        <div class= "actions" >
                            <b><%= t(:description) %></b>
                            <%= @visitation.description %>
                        </div>

                        <br> <p>
                            <% if (current_user.is_employee)%>
                            <div class= "actions" >
                                <%= link_to t(:back), show_visitation_employee_path(@locale), class: "btn btn-primary"  %>
                                <% if (@visitation.status <=> "Aguardando confirmacao") == 0 %>
                                <%= link_to t(:acept_visit), "/#{I18n.locale}"+get_accept_visitation_employee_path(:id => @visitation.id), class: "btn btn-primary" %>
                                <%= link_to t(:refuse_visit), "/#{I18n.locale}"+get_refuse_visitation_employee_path(:id => @visitation.id), class: "btn btn-warning destroy-btn" %>
                                <%end%>
                                <%if (@visitation.status <=> "Agendado") == 0%>
                                <%= link_to t(:cancel_visit), "/#{I18n.locale}"+get_cancel_visitation_employee_path(:id => @visitation.id), class: "btn btn-warning destroy-btn" %>
                                <%end%>
                                <% if (@visitation.status <=> "Cancelado por funcionario") == 0 ||
                                    (@visitation.status <=> "Cancelado pelo usuario") == 0 ||
                                    (@visitation.status <=> "Recusado por funcionario") == 0 %>
                                    <%= link_to t(:remove_visit), "/#{I18n.locale}"+get_delete_visitation_employee_path(:id => @visitation.id), class: "btn btn-warning destroy-btn" %>
                                    <%end%>
                                    <%else%>
                                    <a id="back_space_new" >
                                        <%= link_to 'Voltar', "/#{I18n.locale}"+show_visitation_employee_path, class: "btn btn-primary"  %>
                                        <% if (@visitation.status <=> "Aguardando confirmacao") == 0 %>
                                        <a id="back_space_new" >
                                            <br><br>
                                            <%= link_to t(:cancel_visit), "/#{I18n.locale}"+get_cancel_visitation_user_path(:id => @visitation.id), class: "btn btn-warning destroy-btn" %>
                                            <% end %>
                                        </div>
                                        <%end%>
                                    </div>
                                </div>
                            </div>
                        </body>

JBB-Web/app/views/visitations/index_user.html.erb
<body>
    <head>
        <link href="/vendor/bootstrap/css/bootstrap.css" rel="stylesheet">
        <link href="css/creative.css" rel="stylesheet">
    </head>
    <body id="aplication-body">
        <section id="services">
            <div class="container">
                <div class="row">
                    <div class="col-lg-12 text-center">
                        <h2 class="section-heading"><%= t(:information_visit) %></h2>
                        <hr class="primary">
                    </div>
                </div>
            </div>
            <div class="col-md-6 col-md-offset-3">
            </div>
            <div class="container">
                <div class="row">
                    <div class="col-md-6 col-md-offset-3">
                        <br>
                        <div class = "actions" >
                            <b><%= t(:date_schedule) %></b>
                            <%= l(@visitation.date, format: :long) %>
                        </div>
                        <br>
                        <div class = "actions" >
                            <b><%= t(:scheduled_period) %></b>
                            <%= @visitation.period %>
                        </div>
                        <br>
                        <div class = "actions" >
                            <b><%= t(:status) %></b>
                            <%= @visitation.status %>
                        </div>
                        <br>
                        <div class = "actions" >
                            <b><%= t(:number_visitors) %></b>
                            <%= @visitation.visitants_amount %>
                        </div>
                        <br>
                        <div class = "actions" >
                            <b><%= t(:number_paying_visitors) %></b>
                            <%= @visitation.visitants_paying %>
                        </div>
                        <br>
                        <div class = "actions" >
                            <b><%= t(:visit_price) %></b>
                            <%= @visitation.visitation_cost %>
                        </div>
                        <br>
                        <div class= "actions" >
                            <b><%= t(:description) %></b>
                            <%= @visitation.description %>
                        </div>

                        <br> <p>
                                    <%= link_to t(:generate_pdf), visitations_path(format: 'pdf', :id => @visitation.id), class: "btn btn-primary"%>
                                    <a id="back_space_new" >
                                        <%= link_to t(:back), "/#{I18n.locale}"+show_visitation_user_path, class: "btn btn-primary"  %>
                                        <% if (@visitation.status <=> "Aguardando confirmacao") == 0 %>
                                        <a id="back_space_new" >
                                            <br><br>
                                            <%= link_to t(:cancel_visit), "/#{I18n.locale}"+get_cancel_visitation_user_path(:id => @visitation.id), class: "btn btn-warning destroy-btn" %>
                                            <% end %>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </body>

JBB-Web/app/views/visitations/new.html.erb
<body id="page-top">
    <head>
        <link href="/vendor/bootstrap/css/bootstrap.css" rel="stylesheet">
        <link href="css/creative.css" rel="stylesheet">
    </head>
    <body id="aplication-body">
        <section id="services">
            <div class="container">
                <div class="row">
                    <div class="col-lg-12 text-center">
                        <h2 class="section-heading"><%= t(:visit_request) %></h2>
                        <hr class="primary">
                    </div>
                </div>
            </div>
            <div class="col-md-6 col-md-offset-3">
                <div class = "container">
                    <p><%= t(:fill_update) %></p>
                </div>
            </div>
            <div class="container">
                <div class="row">
                    <div class="col-md-6 col-md-offset-3">
                        <% flash.each do |key, value| %>
                        <div class="alert alert-<%= key %>"><%= value %></div>
                        <% end %>
                        <%= form_for @visitation do |f| %>
                        <% if @visitation.errors.any? %>
                        <div id="error_explanation">
                            <div class="alert-error">
                                <%= t(:form_has) %> <%= pluralize(@visitation.errors.count, "erro") %>.
                            </div>
                            <ul>
                                <% @visitation.errors.full_messages.each do |msg| %>
                                <li><%= msg %></li>
                                <% end %>
                            </ul>
                        </div>
                        <% end %>
                        <br>
                        <div class = "field" >
                            <h0><b><%= t(:date_schedule) %></b></h0> &nbsp
                            <%= f.date_select :date, default: Date.today, start_year: Date.today.year %>
                        </div>
                        <br>
                        <div class = "field">
                            <h0><b><%= t(:scheduled_period) %></b></h0> <br>
                            <%= f.radio_button(:period, "Matutino") %>
                            <%= f.label(:period, t(:morning_period)) %>
                            &nbsp &nbsp &nbsp
                            <%= f.radio_button(:period, "Vespertino") %>
                            <%= f.label(:period, t(:afternoon_period)) %>
                        </div>
                        <br>
                        <div class = "form-inline" >
                            <div class = "form-group">
                                <h0><b><%= t(:objective_visit) %></b></h0> &nbsp
                                <%objectives = [[t(:education), "Educacao"], [t(:research), "Pesquisa"], [t(:recreation), "Lazer"]] %>
                                &nbsp &nbsp
                                <%= f.select :objective, objectives%>
                                &nbsp &nbsp &nbsp &nbsp &nbsp &nbsp &nbsp &nbsp &nbsp &nbsp &nbsp &nbsp &nbsp
                                <h0><b><%= t(:spaces_to_visit) %></b></h0>
                                &nbsp&nbsp
                                <%spaces_jbb = [[t(:tracks), "Trilhas"],[t(:spaces), "Espaco JBB"], [t(:both_options), "Ambos"]] %>
                                <%= f.select :spaces, spaces_jbb, class: 'form-control'%>
                            </div>
                        </div>
                        <br>
                        <div class="form-inline">
                            <h0><b><%= t(:number_visitors) %></b></h0> &nbsp &nbsp
                            <div class = "form-group" style="width: 100px">
                                <%= f.number_field :visitants_amount, min: 1, max: 45, width: 10, :required => true, class: 'form-control'%>
                            </div>

                            <h0><b><%= t(:age_of_visitors) %></b></h0> &nbsp 
                            <div class = "form-group" style="width: 180px">
                                <%= f.number_field :groups_age, :required => true, min: 10, max: 100, class: 'form-control' %>
                            </div>
                            <br>
                            <br>
                            <h0><b><%= t(:visitors_over_12_years) %></b></h0>
                            <div class = "form-group" style="width: 180px"> &nbsp &nbsp
                                <%= f.number_field :visitants_paying, :required => true, min: 0, max: 45, class: 'form-control' %>
                            </div>
                        </div>
                        <br>
                        <div class = "field">
                            <h0><b><%= t(:social_reason) %></b></h0> <br>
                            <%= f.radio_button(:visitation_type, "Grupo de Inclusão") %>
                            <%= f.label(:visitation_type, t(:inclusion_grup)) %>
                            &nbsp &nbsp &nbsp &nbsp &nbsp &nbsp &nbsp &nbsp &nbsp &nbsp &nbsp &nbsp &nbsp &nbsp &nbsp
                            <%= f.radio_button(:visitation_type, "Escola publica", :onclick=>"showMe('Escolas')") %>
                            <%= f.label(:visitation_type, t(:public_school)) %>
                            &nbsp &nbsp &nbsp &nbsp &nbsp &nbsp &nbsp &nbsp &nbsp &nbsp &nbsp &nbsp &nbsp &nbsp &nbsp
                            <%= f.radio_button(:visitation_type, "Escola privada", :onclick=>"showMe('Escolas')") %>
                            <%= f.label(:visitation_type, t(:private_school)) %>
                        </div>
                        <br>
                        <div id="Escolas">
                            <div class = "field">
                                <h0><b><%= t(:want_guide) %></b></h0> <br>
                                &nbsp &nbsp &nbsp &nbsp &nbsp &nbsp <%= f.radio_button(:has_guide, true, :checked => true) %>
                                <%= f.label t(:yes_answer_guide) %> <br>
                                &nbsp &nbsp &nbsp &nbsp &nbsp &nbsp <%= f.radio_button(:has_guide, false) %>
                                <%= f.label t(:no_answer_guide) %>
                            </div>
                        </div>
                        <br>
                        <div class = "field" >
                            <h0><b><%= t(:description) %></b></h0>
                            <%=f.text_area :description, :cols => "50", :rows => "5", :required => true, class: 'form-control'%>
                        </div>
                        <br>
                        <div class="actions">
                            <%= f.submit t(:register), id:'registration', class: "btn btn-primary"%>
                            <a id="space" >
                                <%= link_to t(:view_schedule), "/#{I18n.locale}"+show_visitation_calendar_path, class: "btn btn-primary"%>
                                <a id="new" >
                                    <%= link_to t(:back), "/#{I18n.locale}/" , id:'registration', class: "btn btn-primary" %>
                                </div>
                                <% end %>
                            </div>
                        </div>
                    </div>
</body>

JBB-Web/app/views/visitations/refuse_visitation_employee.html.erb
<p id="notice"><%= notice %></p>

<%= controller.redirect_to "/#{I18n.locale}"+show_visitation_path %>