JBB-Web/config/routes.rb
Rails.application.routes.draw do

  #mailer
  get '/user_mailers/welcome'
  post '/user_mailers/welcome'

  resources :users


  scope "(:locale)", locale: /en|pt/ do

    #root
    # get '/:locale' => 'welcome#index', :as => 'home'
    # get '/:locale' => 'welcome#index', :as => 'root'
    root 'welcome#index', :as => 'home'
    root 'welcome#index', :as => 'root'

    get '/education_choice' => 'welcome#education_choice'


    #users
    get '/users/new' => 'users#new'
    post '/users/new' => 'users#create', :as => 'create_user'
    get '/users/:id' => 'users#show', :as => 'user_show'
    get '/users/edit/:id' => 'users#edit', :as => 'user_edit'
    get '/users/my_requests/:id' => 'users#my_requests', :as =>'user_my_requests'

    patch '/users/update/', controller: 'users', action: 'update', :as => 'update_user'
    patch '/users/update/:id', controller: 'users', action: 'update_password', :as => 'update_user_password'
    patch '/users/destroy/', controller: 'users', action: 'destroy', :as => 'destroy_user'

    #sessions_login
    get    '/sign_in'   => 'sessions#new'
    post   '/sign_in'   => 'sessions#create', :as => 'sign_in_path'
    get '/sign_out' => 'sessions#destroy'

    #root
    get 'sessions/new'
    get 'trails/new'

    #Visitations
    resources :visitations, :except => [:show, :update, :destroy]

    get 'visitations/home', as: 'home_visitation'
      get 'visitations/show_employee', as: 'show_visitation_employee'
    get 'visitations/show_user', as: 'show_visitation_user'
    get 'visitations/index_employee', as: 'index_visitation_employee'
    get 'visitations/index_user', as: 'index_visitation_user'
    get 'visitations/user_information', as: 'visitations_user_information'

    #Visitation Employee
    get 'visitations/accept_visitation_employee', as: 'get_accept_visitation_employee'
    post 'visitations/accept_visitation_employee', as: 'post_accept_visitation_employee'

    get 'visitations/refuse_visitation_employee', as: 'get_refuse_visitation_employee'
    post 'visitations/refuse_visitation_employee', as: 'post_refuse_visitation_employee'

    get 'visitations/cancel_visitation_employee', as: 'get_cancel_visitation_employee'
    post 'visitations/cancel_visitation_employee', as: 'post_cancel_visitation_employee'

    get 'visitations/delete_visitation_employee', as: 'get_delete_visitation_employee'
    post 'visitations/delete_visitation_employee', as: 'post_delete_visitation_employee'

    #Visitation User
    get 'visitations/advices', as: 'get_visitation_advices'
    get 'visitations/cancel_visitation_user', as: 'get_cancel_visitation_user'
    post 'visitations/cancel_visitation_user', as: 'post_cancel_visitation_user'

    #sessions_login
    get 'visitations/delete_visitation_user', as: 'get_delete_visitation_user'
    post 'visitations/delete_visitation_user', as: 'post_delete_visitation_user'

    get    'sign_in'   => 'sessions#new'
    post   'sign_in'   => 'sessions#create'
    delete '/sign_out' => 'sessions#destroy'
    delete 'sign_out'  => 'sessions#destroy'


    #root 'sessions#new'

    get 'events/new' => 'events#new', as: 'events'
    post 'events/new' => 'events#create', as: 'events_save'
    get 'events/show' => 'events#show', as: 'show_event'
    get 'events/show_user', as: 'show_event_user'
    get 'events/show_employee', as: 'show_event_employee'
    get 'events/index_user'
    get 'events/user_information', as: 'events_user_information'
    get 'events/index_employee', as: 'index_event_employee'
    post 'events/index_employee', as: 'index_event_employee_save'

    #Event Employee
    get 'events/accept_event_employee', as: 'get_accept_event_employee'
    post 'events/accept_event_employee', as: 'post_accept_event_employee'

    get 'events/refuse_event_employee', as: 'get_refuse_event_employee'
    post 'events/refuse_event_employee', as: 'post_refuse_event_employee'

    get 'events/cancel_event_employee', as: 'get_cancel_event_employee'
    post 'events/cancel_event_employee', as: 'post_cancel_event_employee'

    get 'events/delete_event_employee', as: 'get_delete_event_employee'
    post 'events/delete_event_employee', as: 'post_delete_event_employee'

    #event User
    get 'events/cancel_event_user' => 'events#cancel_event_user'
    post 'events/cancel_event_user' => 'events#cancel_event_user'

    #Map
    get 'maps/jbb_map', as: 'get_jbb_map'
    post 'maps/jbb_map', as: 'post_jbb_map'

    # schedule route
    get 'events/index_calendar_month' => 'events#index_calendar_month', as: 'show_event_calendar'
    get 'visitations/index_calendar_month' => 'visitations#index_calendar_month', as: 'show_visitation_calendar'

    get 'events/index_calendar_week' => 'events#index_calendar_week', as: 'show_event_calendar_week'
    get 'visitations/index_calendar_week' => 'visitations#index_calendar_week', as: 'show_visitation_calendar_week'

  end

end

JBB-Web/app/models/event.rb
class Event < ApplicationRecord
	belongs_to :user

	# validation of dates
	validates :date_start, presence: true
	validates :date_end, presence: true

	# validation of times
	validates :time_start, presence: true
	validates :time_end, presence: true

	# validation of description
	validates :description, presence: true, length: { minimum: 5, maximum: 500 }

	# validation of estimated_public
	validates :estimated_public, presence: true, numericality: { greater_than: 0 }

	def set_status_default
		self.status = "Aguardando analise"
	end

	def self.total
		self.sum(:price_payment)
	end

	def canceled_by_employee
		self.status = "Cancelado por funcionario"
	end

	def canceled_by_user
		self.status = "Cancelado pelo usuario"
	end

	def refused_by_employee
		self.status = "Recusado por funcionario"
	end

	def accepted_by_employee
		self.status = "Agendado"
	end
end

JBB-Web/app/controllers/events_controller.rb
class EventsController < ApplicationController
   before_action except: [:new, :create, :show_user, :show_employee, :index_calendar_month, :index_calendar_week] do
    @event = Event.find(params[:id])
  end


  #user
  def new
    @event = Event.new
    @jbb_response = params[:jbb_response_to_request]
  end

  def create
    @event = Event.new(event_params)
    @event.user_id = current_user.id
    @event.set_status_default
    @event.jbb_space_requested = params[:jbb_space_requested].join(', ')
    if @event.save
      UserMailer.change_status_event(@event).deliver_now
      flash[:success] = t(:successful_event_request)
      redirect_to "/#{I18n.locale}"+show_event_user_path
    else
      flash[:warning] = t(:request_not_made)
      render action: :new
    end
  end

  def show_user
    @event = Event.where(user_id: current_user.id)
  end

  def index_user
  end

  #cancel_confirmation
  def cancel_event_user
    puts (params[:id])
    @event.canceled_by_user
    if @event.save
      UserMailer.change_status_event(@event).deliver_now
      flash[:warning] = t(:event_canceled_user)
      redirect_to "/#{I18n.locale}"+show_event_user_path
    end
  end

  #employee
  def show_employee
    @event = Event.all
    @sum_of_payments = Event.total
    period = params[:period]
    select_pdf(EventsPdf.new(period))
  end

  def index_employee
  end

  #refuse_confirmation
  def refuse_event_employee
    @event.refused_by_employee
    @event.jbb_response_to_request = (params[:jbb_response_to_request])
    if @event.save
      UserMailer.change_status_event(@event).deliver_now
      flash[:success] = t(:event_refused)
      redirect_to "/#{I18n.locale}"+show_event_employee_path
    else
      flash[:warning] = t(:not_objectionable_event)
      redirect_to "/#{I18n.locale}"+show_event_employee_path
    end
  end

  #cancel_confirmation
  def cancel_event_employee
    @event.canceled_by_employee
    if @event.save
      UserMailer.change_status_event(@event).deliver_now
      flash[:success] = t(:event_canceled)
      redirect_to "/#{I18n.locale}"+show_event_employee_path
    else
      flash[:warning] = t(:not_cancellable_event)
      redirect_to "/#{I18n.locale}"+show_event_employee_path
    end
  end

  #accept_event
  def accept_event_employee
    @event.accepted_by_employee
    puts "====================================================================="
    puts (@jbb_response)
    @event.jbb_response_to_request = (@jbb_response)
    if @event.save
      UserMailer.change_status_event(@event).deliver_now
      flash[:success] = t(:event_confirmed)
      redirect_to "/#{I18n.locale}"+show_event_employee_path
    else
      flash[:warning] = t(:not_confirmable_event)
      redirect_to "/#{I18n.locale}"+show_event_employee_path
    end
  end

  #delete_event
  def delete_event_employee
    if @event.destroy
      UserMailer.change_status_event(@event).deliver_now
      flash[:success] = t(:event_removed)
      redirect_to "/#{I18n.locale}"+show_event_employee_path
    else
      flash[:warning] = t(:not_removable_event)
      redirect_to "/#{I18n.locale}"+show_event_employee_path
    end
  end


  # schedule filter
  def index_calendar_month
    @events = Event.where(status: "Agendado")
  end

  private
  def event_params
    params.require(:event).permit(:name, :date_start, :date_end, :time_start,
                                  :time_end, :status, :description, :need_eletricity,
                                  :need_water, :people_amount, :jbb_space_requested,
                                  :estimated_public, :other_informations,
                                  :jbb_response_to_request, :name_institute,
                                  :institute_address, :institute_cnpj, :price_payment)
  end

end

JBB-Web/app/views/events/index_calendar_month.html.erb
<body id="page-top">
  <head>
    <link href="/vendor/bootstrap/css/bootstrap.css" rel="stylesheet">
    <link href="css/creative.css" rel="stylesheet">
  </head>
  <body id="aplication-body">
    <section id="services">
      <div class="container">
        <div class="row">
          <div class="col-lg-12 text-center">
            <h2 class="section-heading"><%= t(:event_calendar) %></h2>
            <hr class="primary">
          </div>
        </div>
      </div>
      <div class="col-md-6 col-md-offset-3">
        <div class="actions">
          <%= link_to t(:search_by_week), "/#{I18n.locale}"+show_event_calendar_week_path, class: "btn btn-primary week"%>
        </div>
        <br>
        <%= month_calendar events: @events do |date, events| %>
        <b><%= date.strftime("%d") %></b>
        <% events.each do |event| %>
        <div>
         <br>
         <%= event.jbb_space_requested %>
       </div>
       <% end %>
       <% end %>
       <div class= "actions" >
         <%if current_user%>
        <%= link_to t(:create_event), "/#{I18n.locale}"+events_path, class: "btn btn-primary"%>
        <%end%>
        <a id="calendar">
          <%= link_to t(:back), "/#{I18n.locale}", class: "btn btn-primary back"%>
        </div>
        <br>
      </div>
    </section>
  </body>
</body>

JBB-Web/app/views/events/index_calendar_week.html.erb
<body id="page-top">
  <head>
    <link href="/vendor/bootstrap/css/bootstrap.css" rel="stylesheet">
    <link href="css/creative.css" rel="stylesheet">
  </head>
  <body id="aplication-body">
    <section id="services">
      <div class="container">
        <div class="row">
          <div class="col-lg-12 text-center">
            <h2 class="section-heading"><%= t(:event_calendar) %></h2>
            <hr class="primary">
          </div>
        </div>
      </div>
      <div class="col-md-6 col-md-offset-3">
      <div class="actions">
        <%= link_to t(:search_by_month), "/#{I18n.locale}"+show_event_calendar_path, class: "btn btn-primary"%>
      </div>
      <br>
      <%= week_calendar number_of_weeks: 1 do |date, events| %>
      <b><%= date.strftime("%d") %> </div></b>
      <% events.each do |event| %>
      <div>
       <%= event.jbb_space_requested %>
     </div>
     <% end %>
     <% end %>
     <div class= "actions" >
       <%if current_user%>
      <%= link_to t(:create_event), "/#{I18n.locale}"+events_path, class: "btn btn-primary"%>
      <%end%>
      <a id="calendar" >
        <%= link_to t(:back), "/#{I18n.locale}", class: "btn btn-primary back"%>
      </div>
    </section>
  </body>
</body>

JBB-Web/app/views/events/index_employee.html.erb
<p id="notice"><%= notice %></p>
<body id="page-top">
  <head>
    <link href="/vendor/bootstrap/css/bootstrap.css" rel="stylesheet">
    <link href="css/creative.css" rel="stylesheet">
  </head>
  <body id="aplication-body">
    <section id="services">
      <div class="container">
        <div class="row">
          <div class="col-lg-12 text-center">
            <h2 class="section-heading"><%= t(:event_information) %></h2>
            <hr class="primary">
          </div>
        </div>
      </div>
  <div class="col-md-6 col-md-offset-3">
  </div>
  <div class="container">
    <div class="row">
      <div class="col-md-6 col-md-offset-3">
        <div class = "actions">
          <b><%= t(:user_info) %></b>
          <td><%= link_to @event.user.name, "/#{I18n.locale}/events/user_information?id=#{@event.id}" %></td>
        </div>
        <br>
        <b><%= t(:date_time_start) %></b>
        <div class = "actions">
          <b><%= t(:date_schedule) %></b>
          <%= l(@event.date_start, format: :long) %>
        </div>
        <div class = "actions">
          <b><%= t(:time_schedule) %></b>
          <%= l(@event.time_start, format: :time_only) %>
        </div>
        <br>
        <b><%= t(:date_time_end) %></b>
        <div class = "actions">
          <b><%= t(:date_schedule) %></b>
          <%= l(@event.date_end, format: :long) %>
        </div>
        <div class = "actions">
          <b><%= t(:time_schedule) %></b>
          <%= l(@event.time_end, format: :time_only) %>
        </div>
        <br>
        <div class = "actions">
          <b><%= t(:status) %></b>
          <%= @event.status %>
        </div>
        <br>
        <div class = "actions" >
          <b><%= t(:space_request) %></b>
          <%= @event.jbb_space_requested%>
        </div>
        <br>
        <div class = "actions" >
          <b><%= t(:number_visitors) %></b>
          <%= @event.estimated_public%>
        </div>
        <br>
        <div class= "actions spacing" >
          <b><%= t(:description) %></b>
          <%= @event.description %>
        </div>
        <br>
        <table>
          <tr>
            <td>
              <div class = "actions" >
                <b><%= t(:need_eletricity) %></b>
                <%= @event.need_eletricity%>
              </div>
            </td>
            <td>
              <div class = "actions" >
                &nbsp&nbsp&nbsp&nbsp
                <b><%= t(:need_water) %></b>
                <%= @event.need_water%>
              </div>
            </td>
          </tr>
        </table>
        <br>
        <div class= "actions sp" >
          <b><%= t(:other_informations) %></b>
          <%= @event.other_informations %>
        </div>
        <br>
        <div class= "actions spacing" >
          <b><%= t(:name_institute) %></b>
          <%= @event.name_institute %>
        </div>
        <div class= "actions spacing" >
          <b><%= t(:institute_address) %></b>
          <%= @event.institute_address %>
        </div>
        <div class= "actions spacing" >
          <b><%= t(:institute_cnpj) %></b>
          <%= @event.institute_cnpj %>
        </div><br>
        <br>
          <div class="actions">
              <%= link_to t(:back), "/#{I18n.locale}"+show_event_employee_path, :required => true, class: "btn btn-primary"%>
              <% if (@event.status <=> "Aguardando analise") == 0 %>
                  <%= link_to t(:accept_event), "/#{I18n.locale}"+get_accept_event_employee_path(:id => @event.id), class: "btn btn-primary" %>
                  <%= link_to t(:refuse_event), "/#{I18n.locale}"+get_refuse_event_employee_path(:id => @event.id), class: "btn btn-warning destroy-btn" %>
              <%end%>
              <%if (@event.status <=> "Agendado") == 0%>
                 <%= link_to t(:cancel_event), "/#{I18n.locale}"+get_cancel_event_employee_path(:id => @event.id), class: "btn btn-warning destroy-btn" %>
              <%end%>
              <% if (@event.status <=> "Cancelado por funcionario") == 0 ||
                  (@event.status <=> "Cancelado pelo usuario") == 0 ||
                  (@event.status <=> "Recusado por funcionario") == 0 %>
                  <%= link_to t(:delete_event), "/#{I18n.locale}"+get_delete_event_employee_path(:id => @event.id), class: "btn btn-warning destroy-btn" %>
              <%end%>
          </div>
        </div>
      </div>
    </div>
  </body>

JBB-Web/app/views/events/new.html.erb
<body id="page-top">
    <head>
      <link href="/vendor/bootstrap/css/bootstrap.css" rel="stylesheet">
      <link href="css/creative.css" rel="stylesheet">
    </head>
    <body id="aplication-body">
      <section id="services">
        <div class="container">
          <div class="row">
            <div class="col-lg-12 text-center">
              <div class='calendar'></div>
              <h2 class="section-heading"><%= t(:event_request) %></h2>
              <hr class="primary">
            </div>
          </div>
        </div>
	<div class="col-md-6 col-md-offset-3">
		<div class = "container">
      <p><b><%= t(:event_payment_possibility) %></b></p>
      <br><br>
			<p><%= t(:fill_update) %></p>
		</div>
	</div>
	<div class="container">
		<div class="row">
			<div class="col-md-6 col-md-offset-3">
				<%flash.each do |key, value|%>
				<div class="alert alert-<%= key %>"><%= value %></div>
				<%end%>
				<%=form_for @event do |f|%>
				<%if @event.errors.any?%>
				<div id="error_explanation">
					<div class="alert-error">
						O formulário contém <%=pluralize(@event.errors.count, "erro")%>.
					</div>
					<ul>
						<%@event.errors.full_messages.each do |msg|%>
						<li><%= msg %></li>
						<%end%>
					</ul>
				</div>
				<%end%>
				<br>
				<div class = "field event_date_start_1i">
					<b><%= t(:date_to_start) %></b>
					<%=f.date_select(:date_start) %>
				</div>
				<div class="field">
					<b><%= t(:time_to_start) %></b>
					<%=f.time_select(:time_start, minute_step: 15, start_hour: 8, end_hour: 16)%>
				</div>
				<br>
				<div class = "field">
					<b><%= t(:date_to_end) %></b>
					<%=f.date_select(:date_end)%>
				</div>
				<div class="field">
					<b><%= t(:time_to_end) %></b>
					<%=f.time_select(:time_end, minute_step: 15, start_hour: 8, end_hour: 16)%>
				</div>
        <br>
				<b><%= t(:space_request) %></b>
        <div class = "checkbox" >
          &nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp
          <%= check_box_tag("jbb_space_requested[]", value = "Anfiteatro") %>
          <%= label_tag("jbb_space_requested[]", "Anfiteatro") %>
          <br>
          &nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp
          <%= check_box_tag("jbb_space_requested[]", value = "Área de Piquenique") %>
          <%= label_tag("jbb_space_requested[]", "Área de Piquenique") %>
          <br>
          &nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp
          <%= check_box_tag("jbb_space_requested[]", value = "Biblioteca da Natureza") %>
          <%= label_tag("jbb_space_requested[]", "Biblioteca da Natureza") %>
          <br>
          &nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp
          <%= check_box_tag("jbb_space_requested[]", value = "Casa de Chá") %>
          <%= label_tag("jbb_space_requested[]", "Casa de Chá") %>
          <br>
          &nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp
          <%= check_box_tag("jbb_space_requested[]", value = "Centro de Excelência do Cerrado") %>
          <%= label_tag("jbb_space_requested[]", "Centro de Excelência do Cerrado") %>
          <br>
          &nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp
          <%= check_box_tag("jbb_space_requested[]", value = "Centro de Visitantes") %>
          <%= label_tag("jbb_space_requested[]", "Centro de Visitantes") %>
          <br>
          &nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp
          <%= check_box_tag("jbb_space_requested[]", value = "Estufas") %>
          <%= label_tag("jbb_space_requested[]", "Estufas") %>
          <br>
          &nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp
          <%= check_box_tag("jbb_space_requested[]", value = "Horto Medicinal") %>
          <%= label_tag("jbb_space_requested[]", "Horto Medicinal") %>
          <br>
          &nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp
          <%= check_box_tag("jbb_space_requested[]", value = "Jardim de Cheiros") %>
          <%= label_tag("jbb_space_requested[]", "Jardim de Cheiros") %>
          <br>
          &nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp
          <%= check_box_tag("jbb_space_requested[]", value = "Jardim Evolutivo") %>
          <%= label_tag("jbb_space_requested[]", "Jardim Evolutivo") %>
          <br>
          &nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp
          <%= check_box_tag("jbb_space_requested[]", value = "Jardim Japonês") %>
          <%= label_tag("jbb_space_requested[]", "Jardim Japonês") %>
          <br>
          &nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp
          <%= check_box_tag("jbb_space_requested[]", value = "Orquidário") %>
          <%= label_tag("jbb_space_requested[]", "Orquidário") %>
          <br>
          &nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp
          <%= check_box_tag("jbb_space_requested[]", value = "Unidade de Permacultura") %>
          <%= label_tag("jbb_space_requested[]", "Unidade de Permacultura") %>
          <br><br>
          &nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp
          <%= check_box_tag("jbb_space_requested[]", value = "Não conheço os espaços do Jardim Botânico") %>
          <%= label_tag("jbb_space_requested[]", t(:dont_know_jbb_spaces)) %>
          <br><br>
        </div>
				<div class="form-inline">
					<b><%= t(:number_visitors) %></b> &nbsp&nbsp&nbsp
					<div class = "form-group" style="width: 200px">
						<%= f.number_field :estimated_public, min: 1, width: 10, :required => true, class: 'form-control'%>
					</div>
				</div>
				<br>
				<div class = "field">
					<table border = '0'>
						<td>
							<tr>
                <div class = "form-inline">
                  <b><%= t(:need_eletricity) %></b>
                  <a id="back_space_new" > </a>
  								<b><%= t(:need_water) %></b>
                </div>
							</tr>
							<tr>
                <div class = "form-inline">
                  <%= f.radio_button(:need_eletricity, "Sim")%>
  								<%= f.label(:need_eletricity, t(:yes_answer))%> &nbsp&nbsp&nbsp&nbsp
  								<%= f.radio_button(:need_eletricity, "Nao") %>
  								<%= f.label(:need_eletricity, t(:no_answer))%>
                  <a id="back_space_new" > </a> &nbsp&nbsp&nbsp&nbsp &nbsp&nbsp&nbsp&nbsp &nbsp&nbsp&nbsp&nbsp
  								<%= f.radio_button(:need_water, "Sim")%>
  								<%= f.label(:need_water, t(:yes_answer))%> &nbsp&nbsp&nbsp&nbsp
  								<%= f.radio_button(:need_water, "Nao") %>
  								<%= f.label(:need_water, t(:no_answer)) %>
                </div>
  						</tr>
						</td>
					</table>
				</div>
				<br>
				<div class = "field" >
					<b><%= t(:other_informations) %></b>
					<%=f.text_area :other_informations, :cols => "50", :rows => "5", class: 'form-control'%>
				</div>
				<br>
				<div class = "field" >
					<b><%= t(:description) %></b>
					<%=f.text_area :description, :cols => "50", :rows => "5", :required => true, class: 'form-control'%>
				</div>
				<br><br>
				<p><%= t(:case_institution) %></p>
				<div class="field">
					<b><%= t(:name_institute) %></b>
					<%= f.text_field :name_institute, autocomplete: "off", class: 'form-control', placeholder: t(:placeholder_name_institute) %>
				</div>
				<br>
				<div class="field">
					<b><%= t(:institute_address) %></b>
					<%= f.text_field :institute_address, autocomplete: "off", class: 'form-control', placeholder: t(:placeholder_institute_address) %>
				</div>
				<br>
				<div class="field">
					<b><%= t(:institute_cnpj) %></b>
					<%= f.text_field :institute_cnpj, autocomplete: "off", class: 'form-control', placeholder: t(:placeholder_institute_cnpj) %>
				</div>
				<br>
				<div class="actions">
					<%= f.submit t(:register),id:'registration', class: "btn btn-primary"%>
					<a id="space" >
					<%= link_to t(:view_schedule), "/#{I18n.locale}"+show_event_calendar_path, class: "btn btn-primary" %>
					<a id="new" >
					<%= link_to t(:back), "/#{I18n.locale}", class: "btn btn-primary"%>
				</div>
				<%end%>
			</div>
		</div>
	</div>
</body>

JBB-Web/app/views/events/show_user.html.erb
<body id="page-top">
  <head>
    <link href="/vendor/bootstrap/css/bootstrap.css" rel="stylesheet">
    <link href="css/creative.css" rel="stylesheet">
  </head>
  <body id="aplication-body">
    <section id="services">
      <div class="container">
        <div class="row">
          <div class="col-lg-12 text-center">
            <h2 class="section-heading"><%= t(:show_event) %></h2>
            <hr class="primary">
          </div>
        </div>
      </div>
    </section>
    <div class="col-md-6 col-md-offset-3">
    </div>
    <div class="container-fluid">
      <div class="row">
        <div class="col-md-10 col-md-offset-1">
          <% flash.each do |key, value| %>
          <div class="alert alert-<%= key %>"><%= value %></div>
          <% end %>
          <% if !@event.empty?%>
          <div class="table-hover">
            <table border=0 class="table" >
              <tr>
                <th><%= t(:date_schedule) %></th>
                <th><%= t(:time_schedule) %></th>
                <th><%= t(:status) %></th>
                <th><%= t(:space_request) %></th>
              </tr>
              <% @event.each do |event| %>
              <tr>
                <td> <%= l(event.date_start, format: :long) %> </td>
                <td> <%= l(event.time_start, format: :time_only) %> </td>
                <td> <%= event.status %> </td>
                <td> <%= event.jbb_space_requested %> </td>
                <td><%= link_to t(:show), "/#{I18n.locale}/events/index_user?id=#{event.id}" %></td>
                <% if (event.status <=> "Aguardando analise") == 0 %>
                <td>
                  <%= link_to t(:cancel_event), controller: "events",
                  action: "cancel_event_user", id: event %>
                </td>
                <%end%>
              </tr>
              <%end%>
            </table>
            <a id="show" >
          <br> <br>
          </div>
          <% else %>
          <div class="row">
            <div class="col-lg-12 text-center">
              <h2 class="section-heading"><%= t(:no_scheduled_event) %></h2>
            </div>
          </div>
          <% end %>
          <br>
          <div class="action" >
            <a id="show" >
            <a id="back_space_new" >
            <%= link_to t(:back), "/#{@language}/users/my_requests/#{current_user.id}", class: "btn btn-primary" %>
            <a id="back_space_new" >
            <a id="back_space_new" >
            <a id="back_space_new" >
            <%= link_to t(:new_event), events_path, class: "btn btn-primary" %>
            </div>
            <br><br><br>
          </div>
        </div>
      </div>
    </body>
  </body>