JBB-Web/config/routes.rb
Rails.application.routes.draw do

  #mailer
  get '/user_mailers/welcome'
  post '/user_mailers/welcome'

  resources :users


  scope "(:locale)", locale: /en|pt/ do

    #root
    # get '/:locale' => 'welcome#index', :as => 'home'
    # get '/:locale' => 'welcome#index', :as => 'root'
    root 'welcome#index', :as => 'home'
    root 'welcome#index', :as => 'root'

    get '/education_choice' => 'welcome#education_choice'


    #users
    get '/users/new' => 'users#new'
    post '/users/new' => 'users#create', :as => 'create_user'
    get '/users/:id' => 'users#show', :as => 'user_show'
    get '/users/edit/:id' => 'users#edit', :as => 'user_edit'
    get '/users/my_requests/:id' => 'users#my_requests', :as =>'user_my_requests'

    patch '/users/update/', controller: 'users', action: 'update', :as => 'update_user'
    patch '/users/update/:id', controller: 'users', action: 'update_password', :as => 'update_user_password'
    patch '/users/destroy/', controller: 'users', action: 'destroy', :as => 'destroy_user'

    #sessions_login
    get    '/sign_in'   => 'sessions#new'
    post   '/sign_in'   => 'sessions#create', :as => 'sign_in_path'
    get '/sign_out' => 'sessions#destroy'

    #root
    get 'sessions/new'
    get 'trails/new'

    #Visitations
    resources :visitations, :except => [:show, :update, :destroy]

    get 'visitations/home', as: 'home_visitation'
      get 'visitations/show_employee', as: 'show_visitation_employee'
    get 'visitations/show_user', as: 'show_visitation_user'
    get 'visitations/index_employee', as: 'index_visitation_employee'
    get 'visitations/index_user', as: 'index_visitation_user'
    get 'visitations/user_information', as: 'visitations_user_information'

    #Visitation Employee
    get 'visitations/accept_visitation_employee', as: 'get_accept_visitation_employee'
    post 'visitations/accept_visitation_employee', as: 'post_accept_visitation_employee'

    get 'visitations/refuse_visitation_employee', as: 'get_refuse_visitation_employee'
    post 'visitations/refuse_visitation_employee', as: 'post_refuse_visitation_employee'

    get 'visitations/cancel_visitation_employee', as: 'get_cancel_visitation_employee'
    post 'visitations/cancel_visitation_employee', as: 'post_cancel_visitation_employee'

    get 'visitations/delete_visitation_employee', as: 'get_delete_visitation_employee'
    post 'visitations/delete_visitation_employee', as: 'post_delete_visitation_employee'

    #Visitation User
    get 'visitations/advices', as: 'get_visitation_advices'
    get 'visitations/cancel_visitation_user', as: 'get_cancel_visitation_user'
    post 'visitations/cancel_visitation_user', as: 'post_cancel_visitation_user'

    #sessions_login
    get 'visitations/delete_visitation_user', as: 'get_delete_visitation_user'
    post 'visitations/delete_visitation_user', as: 'post_delete_visitation_user'

    get    'sign_in'   => 'sessions#new'
    post   'sign_in'   => 'sessions#create'
    delete '/sign_out' => 'sessions#destroy'
    delete 'sign_out'  => 'sessions#destroy'


    #root 'sessions#new'

    get 'events/new' => 'events#new', as: 'events'
    post 'events/new' => 'events#create', as: 'events_save'
    get 'events/show' => 'events#show', as: 'show_event'
    get 'events/show_user', as: 'show_event_user'
    get 'events/show_employee', as: 'show_event_employee'
    get 'events/index_user'
    get 'events/user_information', as: 'events_user_information'
    get 'events/index_employee', as: 'index_event_employee'
    post 'events/index_employee', as: 'index_event_employee_save'

    #Event Employee
    get 'events/accept_event_employee', as: 'get_accept_event_employee'
    post 'events/accept_event_employee', as: 'post_accept_event_employee'

    get 'events/refuse_event_employee', as: 'get_refuse_event_employee'
    post 'events/refuse_event_employee', as: 'post_refuse_event_employee'

    get 'events/cancel_event_employee', as: 'get_cancel_event_employee'
    post 'events/cancel_event_employee', as: 'post_cancel_event_employee'

    get 'events/delete_event_employee', as: 'get_delete_event_employee'
    post 'events/delete_event_employee', as: 'post_delete_event_employee'

    #event User
    get 'events/cancel_event_user' => 'events#cancel_event_user'
    post 'events/cancel_event_user' => 'events#cancel_event_user'

    #Map
    get 'maps/jbb_map', as: 'get_jbb_map'
    post 'maps/jbb_map', as: 'post_jbb_map'

    # schedule route
    get 'events/index_calendar_month' => 'events#index_calendar_month', as: 'show_event_calendar'
    get 'visitations/index_calendar_month' => 'visitations#index_calendar_month', as: 'show_visitation_calendar'

    get 'events/index_calendar_week' => 'events#index_calendar_week', as: 'show_event_calendar_week'
    get 'visitations/index_calendar_week' => 'visitations#index_calendar_week', as: 'show_visitation_calendar_week'

  end

end

JBB-Web/app/models/user.rb
class User < ApplicationRecord

  require "cpf_cnpj"

  has_secure_password
  has_many :events
  has_many :visitations
  has_many :phones, :inverse_of => :user

  accepts_nested_attributes_for :phones

  attr_accessor :remember_token

  validates :password_digest, presence: true, length: {
    minimum: 6
  }

  validate :valid_name, :valid_gender, :valid_email, :valid_cpf

  $SPECIAL_CARACTERS = ['!', '@', '#', '$', '%', '¨', '*', '(', ')', '-', '+',
    '=', '§', '_', '²', '¹', '³', '¢', '¬', '{', '[', ']', '}' '?', ':', ';',
    '.', ',', '°', 'º', '|', '\\', '/', '^', '~', '´', '`', '"', '\'', '<', '>']
  $NUMBERS = ['0', '1', '2', '3', '4', '5', '6', '7', '8', '9']

  #is employee
  def set_as_not_employee
    self.is_employee = false
  end


  #user_name
  def valid_name
    if (self.name == nil)
      errors.add(:name, I18n.t(:fill_correct_name))
    end

    #puts "nome avaliado: #{name}\n\n\n"
    $SPECIAL_CARACTERS.each do |caracter|
      if (self.name.include? caracter)
        errors.add(:name, I18n.t(:invalid_characters_in_name))
      end
    end

    $NUMBERS.each do |number|
      if (self.name.include? number)
        errors.add(:name, I18n.t(:numbers_in_name))
      end
    end

    if (self.name.length < 3)
      errors.add(:name, I18n.t(:short_name))
    end

    unless (self.name.include? ' ')
      errors.add(:name, I18n.t(:missing_surname))
    end
  end


  #cpf
  validates :cpf, uniqueness: {
    message: I18n.t(:already_used_cpf)
  }

  def valid_cpf
    if (self.cpf == nil)
      errors.add(:cpf, I18n.t(:blank_cpf_field))
    elsif ((CPF.valid?(self.cpf)) == false)
      errors.add(:cpf, I18n.t(:invalid_cpf_number))
    end
  end

  #email
  validates :email, uniqueness: {
    message: I18n.t(:already_used_email)
  }


  def valid_cpf
    if ((self.cpf <=> '111.111.111-11') == 0 ||
      (self.cpf <=> '222.222.222-22') == 0 ||
      (self.cpf <=> '333.333.333-33') == 0 ||
      (self.cpf <=> '444.444.444-44') == 0 ||
      (self.cpf <=> '555.555.555-55') == 0 ||
      (self.cpf <=> '666.666.666-66') == 0 ||
      (self.cpf <=> '777.777.777-77') == 0 ||
      (self.cpf <=> '888.888.888-88') == 0 ||
      (self.cpf <=> '999.999.999-99') == 0 ||
      (self.cpf <=> '000.000.000-00') == 0 )
      errors.add(:cpf, I18n.t(:invalid_cpf_number))
    end

    if (self.cpf == nil)
      errors.add(:cpf, I18n.t(:blank_cpf_field))
    elsif ((CPF.valid?(self.cpf)) == false)
      errors.add(:cpf, I18n.t(:invalid_cpf_number))
    end
  end


  #email validates
  validates :email, uniqueness: {
    message: I18n.t(:already_used_email)
  }


  def valid_email
    if (self.email == nil)
      errors.add(:email, I18n.t(:blank_email_field))
    elsif (self.email.length < 10 || self.email.length > 255)
      errors.add(:email, I18n.t(:invalid_email))
    end

    unless (validates_format_of :email,:with =>
      /[0-9a-z][0-9a-z.]+[0-9a-z]@[0-9a-z][0-9a-z.-]+[0-9a-z]/i)
      errors.add(:email, I18n.t(:invalid_email_format))
    end
  end



  #gender
  def valid_gender
    if (self.gender == nil)
      errors.add(:gender, I18n.t(:blank_gender_field))
    end

    unless ((gender.capitalize <=> 'Masculino') == 0 ||
      (gender.capitalize <=> 'Feminino') == 0 ||
      (gender.capitalize <=> 'Outro') == 0
      )

      errors.add(:gender, I18n.t(:invalid_gender))
    end
  end

  #Password
  def User.digest(string)
    cost = ActiveModel::SecurePassword.min_cost ? BCrypt::Engine::MIN_COST :
    BCrypt::Engine.cost
    BCrypt::Password.create(string, cost: cost)
  end

  def User.new_token
    SecureRandom.urlsafe_base64
  end

  def remember
    self.remember_token = User.new_token
    update_attribute(:remember_digest, User.digest(remember_token))
  end

  def authenticate?(remember_token)
    return false if remember_digest.nil?
    BCrypt::Password.new(remember_digest).is_password?
  end

  def forget
    update_attribute(:remember_digest, nil)
  end
end

JBB-Web/app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action only: [:edit, :update, :show] do
    @user = User.find(params[:id])
  end

  #New user
  def new
    @user = User.new
		@phone = @user.phones.build
  end


  #Creating a new user
  def create
  	@user = User.new(user_params)
    @user.set_as_not_employee
  	if @user.save
      UserMailer.welcome(@user).deliver_now
			@phone = @user.phones.build(params[:phone])
      session[:user_id] = @user.id
      flash[:success] = t(:sucessful_user_registration)
      redirect_to "/#{I18n.locale}/"
  	else
  		render 'new'
    end
  end

  # Editing the user profile
  def edit
    if @user != current_user
      redirect_to "/#{I18n.locale}/"
    end
  end

  #Update User
  def update
    if @user.update(user_params)
      flash[:success] = t(:sucessful_profile_update)
      redirect_to @user
    else
      flash[:warning] = t(:error_profile_update)
    end
  end

  #Show the User
  def show
    @phone = @user.phones.all
     if @user != current_user
       redirect_to "/#{I18n.locale}/"
     end
  end

  #Visitation's and event's request
  def my_requests
    @user = current_user
  end

  #Delete the user
  def destroy
    current_user.destroy
    session[:user_id] = nil
    flash[:warning] = t(:sucessful_profile_remove)
    redirect_to "/#{I18n.locale}/"
  end

  private
  def user_params
    params[:user].permit(:name, :email, :password, :is_employee, :cpf, :birth, :gender, phones_attributes: :phone)
	end
end

JBB-Web/app/views/users/edit.html.erb
<body id="aplication-body">
    <head>
      <link href="/vendor/bootstrap/css/bootstrap.css" rel="stylesheet">
      <link href="css/creative.css" rel="stylesheet">
    </head>
    <body id="aplication-body">
      <section id="services">
        <div class="container">
          <div class="row">
            <div class="col-lg-12 text-center">
              <h2 class="section-heading"><%=t(:update_profile)%></h2>
              <hr class="primary">
            </div>
          </div>
        </div>
  <div class="container">
    <div class = "row">
      <div class="col-md-6 col-md-offset-3">
        <p><%=t(:fill_update)%></p>
      </div>
    </div>
  </div>
  <div class="container">
    <div class="row">
      <div class="col-md-6 col-md-offset-3">
      <% flash.each do |key, value| %>
        <div class="alert alert-<%= key %>"><%= value %></div>
      <% end %>
        <%= form_for @user do |f| %>
          <% if @user.errors.any? %>
            <div id="error_explanation">
              <div class="alert-error">
                <%=t(:form_has)%> <%= pluralize(@user.errors.count, "erro") %>.
              </div>
              <ul>
                <% @user.errors.full_messages.each do |msg| %>
                <li><%= msg %></li>
                <% end %>
              </ul>
            </div>
          <% end %>
          <div class="field">
            <%= f.label t(:name) %>
            <%= f.text_field :name, :required => true, autocomplete: "off", class: 'form-control', placeholder: t(:placeholder_name) %>
          </div>
          <br>
          <div class="field">
            <%= f.label t(:email) %>
            <%= f.email_field :email, :required => true, autocomplete: "off", class: 'form-control', placeholder: t(:placeholder_email) %>
          </div>
          <br>
          <div class="field">
            <%= f.label t(:password) %>
            <%= f.password_field :password, :required => true, autocomplete: "off", class: 'form-control' , placeholder: t(:placeholder_password) %>
          </div>
          <br>
          <div class="field">
            <%= f.label :CPF %>
            <%= f.text_field :cpf, :required => true, autocomplete: "off", id: 'cpf', class: 'form-control',
                             placeholder: 'Ex.: 000.000.000-00', maxlength: '14',
                             :onkeypress => "CpfMask(this)", :onblur => "ValidateCPF(this)"%>
          </div>
          <br>
          <%= f.fields_for :phones do |ff| %>
            <div class="field">
              <%= ff.label t(:phone) %>
              <%= ff.text_field :phone, :required => true, autocomplete: "off", id: 'phone', class: 'form-control',
                                placeholder: '(00)00000-0000' , maxlength: '14',
                                :onkeypress => "PhoneMask(this)", :onblur => "ValidatePhone(this)"%>
            </div>
          <% end %>
          <br>
          <div class="form-group">
            <label for="gender"><%=t(:gender)%></label>
            <%genders = [["", ""], [t(:female), "Feminino"], [t(:male), "Masculino"], [t(:other), "Outro"]] %>
            <%= f.select :gender, genders, :required => true, class: 'form-control' %>
          </div>
          <div class="field">
            <%= f.label t(:birth) %>
            <%= f.text_field :birth, :required => true, autocomplete: "off", id: 'date', class: 'form-control',
                             value: @user.birth.strftime("%d/%m/%Y"), placeholder: t(:placeholder_birth), maxlength: '10',
                             :onkeypress => "DateMask(this)", :onblur => "ValidateDate(this)"%>
          </div>
          <br>
          <div class="actions">
            <%= f.submit t(:update), class: "btn btn-primary"%>
            <a id="update" >
            <a href="/<%= @language %>/users/<%= current_user.id %>" class="btn btn-primary"><%=t(:back)%></a>
          </div>
        <% end %>
      </div>
    </div>
  </div>
  <br>
</body>

JBB-Web/app/views/users/my_requests.html.erb
<!DOCTYPE html>
<html lang="en">
<head>
  <link href="/vendor/bootstrap/css/bootstrap.css" rel="stylesheet">
  <link href="css/creative.css" rel="stylesheet">
  <link rel="stylesheet" href="http://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.6.3/css/font-awesome.min.css">
</head>
<body id="aplication-body">
  <section id="services">
    <div class="container">
      <div class="row">
        <div class="col-lg-12 text-center">
            <% if current_user.is_employee %>
              <h2 class="section-heading"><%= t(:just_request) %></h2>
            <% else %>
              <h2 class="section-heading"><%= t(:requests) %></h2>
            <% end%>
          <hr class="primary">
        </div>
      </div>
    </div>
    <br>
    <div class="container">
      <div class="row">
        <div class="col-md-6 text-center">
          <div class="service-box">
                <% if current_user.is_employee %>
                    <a href="/<%= @language %>/visitations/show_employee">
                  <% else %>
                    <a href="/<%= @language %>/visitations/show_user">
                  <% end%>
            <i class="fa fa-4x fa-map-marker text-primary sr-icons"></i>
            <% if current_user %>
             <% if current_user.is_employee %>
             <h3><%= t(:manage_visit) %></h3>
            <p class="text-muted"><%= t(:manage_visit2) %></p>
             <% else %>
            <h3><%= t(:manage_visit) %></h3>
            <p class="text-muted"><%= t(:viewing_editing_visits)%></p>
            <% end%>
          </div>
        </div>
      <div class="col-md-6 text-center">
        <div class="service-box">
            <% if current_user.is_employee %>
              <a href="/<%= @language %>/events/show_employee">
            <% else %>
              <a href="/<%= @language %>/events/show_user">
            <% end%>
          <i class="fa fa-4x fa-users text-primary sr-icons"></i>
          <% if current_user %>
             <% if current_user.is_employee %>
             <h3><%= t(:manage_event) %></h3>
            <p class="text-muted"><%= t(:manage_event2)%></p>
             <% else %>
            <h3><%= t(:manage_event) %></h3>
            <p class="text-muted"><%= t(:viewing_editing_events)%></p>
            <% end%>
            <% end%>
        </div>
      </div>
      <% end %>
</section>
</body>
</html>

JBB-Web/app/views/users/new.html.erb
<body id="aplication-body">
  <head>
    <link href="/vendor/bootstrap/css/bootstrap.css" rel="stylesheet">
    <link href="css/creative.css" rel="stylesheet">
  </head>
  <body id="aplication-body">
    <section id="services">
      <div class="container">
        <div class="row">
          <div class="col-lg-12 text-center">
            <h2 class="section-heading"><%= t(:sign_up_user) %></h2>
            <hr class="primary">
          </div>
        </div>
      </div>
      <div class="container">
        <div class = "row">
          <div class="col-md-6 col-md-offset-3">
            <p><%= t(:fill_update) %></p>
          </div>
        </div>
      </div>
      <div class="container">
        <div class="row">
          <div class="col-md-6 col-md-offset-3">
            <% flash.each do |key, value| %>
            <div class="alert alert-<%= key %>"><%= value %></div>
            <% end %>
            <%= form_for @user, url: '/users' do |f| %>
            <% if @user.errors.any? %>
            <div id="error_explanation">
              <div class="alert-error">
                <%= t(:form_has) %> <%= pluralize(@user.errors.count, "erro") %>.
              </div>
              <ul>
                <% @user.errors.full_messages.each do |msg| %>
                <li><%= msg %></li>
                <% end %>
              </ul>
            </div>
            <% end %>
            <div class="field">
              <h0><b><%= t(:name) %></b></h0>
              <%= f.text_field :name, :required => true, autocomplete: "off", class: 'form-control', placeholder: t(:placeholder_name) %>
            </div>
            <br>
            <div class="field">
              <h0><b><%= t(:email) %></b></h0>
              <%= f.email_field :email, :required => true, autocomplete: "off", class: 'form-control', placeholder: t(:placeholder_email) %>
            </div>
            <br>
            <div class="field">
              <h0><b><%= t(:password) %></b></h0>
              <%= f.password_field :password, :required => true, autocomplete: "off", class: 'form-control' , placeholder: t(:placeholder_password) %>
            </div>
            <br>
            <div class="field">
              <h0><b><%= "CPF:" %></b></h0>
              <%= f.text_field :cpf, :required => true, autocomplete: "off", id: 'cpf', class: 'form-control',
              placeholder: 'Ex.: 000.000.000-00', maxlength: '14',
              :onkeypress => "CpfMask(this)", :onblur => "ValidateCPF(this)"%>
            </div>
            <br>
            <%= f.fields_for :phones do |ff| %>
            <div class="field">
              <h0><b><%= t(:phone) %></b></h0>
              <%= ff.text_field :phone, :required => true, autocomplete: "off", id: 'phone', class: 'form-control',
              placeholder: '(00)00000-0000' , maxlength: '14',
              :onkeypress => "PhoneMask(this)", :onblur => "ValidatePhone(this)"%>
            </div>
            <% end %>
            <br>
            <div class="form-group">
              <label for="gender"><%= t(:gender) %></label>
              <%genders = [["", ""], [t(:female), "Feminino"], [t(:male), "Masculino"], [t(:other), "Outro"]] %>
              <%= f.select :gender, genders, :required => true, class: 'form-control' %>
            </div>
            <div class="field">
              <%= f.label t(:birth) %>
              <%= f.text_field :birth, :required => true, autocomplete: "off", id: 'date',class: 'form-control',
              placeholder: t(:placeholder_birth), maxlength: '10',
              :onkeypress => "DateMask(this)", :onblur => "ValidateDate(this)"%>
            </div>
            <br>
            <div class="actions">
              <%= f.submit t(:sign_up),id: 'registration', class: "btn btn-primary"%>
              <a id="update_new" >
                <a href="/<%= @language %>/" class="btn btn-primary"><%=t(:back)%></a>
              </div>
              <% end %>
            </div>
          </div>
        </div>
        <br>
      </body>

JBB-Web/app/views/users/show.html.erb
<body id="aplication-body">
    <br>
    <br>
    <br>
    <head>
      <link href="/vendor/bootstrap/css/bootstrap.css" rel="stylesheet">
      <link href="css/creative.css" rel="stylesheet">
    </head>
  <div class="container">
  	<div class="row">
      <div class="col-md-6 col-md-offset-3">
      <% flash.each do |key, value| %>
        <div class="alert alert-<%= key %>"><%= value %></div>
      <% end %>
      <div class="col-lg-12 text-center">
        <h2 class="section-heading"><%= t(:profile) %><%= current_user.name %></h2>
        <hr class="primary">
      </div>
       <p>
        <b> <%= t(:email) %> </b>
        <%= current_user.email %>
      </p>
      <p>
        <b> CPF: </b>
        <%= current_user.cpf %>
      </p>
      <p>
        <b> <%= t(:phone) %> </b>
        <% current_user.phones.each do |p| %>
          <%= p.phone %>
        <% end %>
      </p>
      <p>
        <b> <%= t(:gender) %> </b>
        <% if (@user.gender <=> "Feminino") == 0 %>
        <%= t(:female) %>
        <%end%>
        <% if (@user.gender <=> "Masculino") == 0 %>
        <%= t(:male) %>
        <%end%>
        <% if (@user.gender <=> "Outro") == 0 %>
        <%= t(:other) %>
        <%end%>
      </p>
      <p>
        <b> <%= t(:birth) %> </b>
        <%= l(current_user.birth, format: :long) %>
      </p>
      <div class="actions">
        <%= link_to  t(:edit), user_edit_path(@language,current_user), class: "btn btn-primary" %>
        <a id="space" >
        <a href="/<%= @language %>/" class="btn btn-primary"><%=t(:back)%></a>
        <a id="new" >
        <%= link_to t(:exclude), current_user, method: :delete, data: { confirm: t(:confirm_delete_user) }, class: "btn btn-warning destroy-btn"%>
      </div>
      </div>
    </div>
  </div>
</body>